version: "3"
services:
  mysql:
    image: mysql:8.0.14
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./mysql/custom:/etc/mysql/conf
      -  /var/tmp/mysql20221010/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  kanpoApp:
    depends_on:
      - mysql
    image:  kanpo-app-02
    networks:
      - default
    ports:
      - 8080:8080
    restart: always
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/${DB_NAME}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.initialization-mode=always
networks:
  default:
    name: my-app-net